### ISSUE TITLE
[T&I] General Inference

### ISSUE THREAD

**Issue by ananya-singhh** [PurdueDualityLab/tf-maskformer#11]
### Sub-tasks
- [x] Find and understand the implementation of general inference in the paper + codebase (including other papers / repos to look into)
- [x] Find any pre-existing code in TensorFlow codebase
- [x] Implement the general inference
- [ ] Implement helper class
- [ ] Write test cases
