### ISSUE TITLE
[T&I] Metrics

### ISSUE THREAD

**Issue by ananya-singhh** [PurdueDualityLab/tf-maskformer#14]
### Sub-tasks
- [x] Find all metrics from the paper
- [x] Find which ones are implemented in TensorFlow already
- [x] For those not implemented in TensorFlow, find the PyTorch equivalent for reference
- [ ] Verify the implementations are the same as the ones used in MaskFormer
    - [x] PQ (things + stuff)
    - [x] SQ
    - [x] RQ
    - [ ] FPS
    - [ ] FLOPs
    - [x] # params
- [ ] Implement metrics
    - [x] PQ (things + stuff)
    - [x] SQ
    - [x] RQ
    - [ ] FPS
    - [ ] FLOPs
    - [x] # params

[Here](https://github.com/tensorflow/models/tree/master/official/vision/evaluation) are some of the metrics from the codebase.
